# Replace the text below to customize your site
site_name: Marc Parés — Iaac
site_description: Master in Design for Emergent Futures
site_author: Marc Parés
copyright: Marc Parés  ©  2022
repo_name: 'Marc Parés'
site_url: 'https://paresmarc.github.io/MDEF/'
repo_url: 'https://paresmarc.github.io/MDEF/'

nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
      - Design Space: project/design-space.md

#  - Design Studio:
#      - Bootcamp: DS/01-Bootcamp.md
#      - Areas of Interventions: DS/02-Areas of Interventions.md
#      - Roles of Prototyping: DS/03-Roles of Prototyping.md
#      - Documentation: DS/04-Documentation.md

  - Reflections:
    - Term 1:
      - Bootcamp: DS/01-Bootcamp.md
      - Atlas of Weak Signals: Term1/01-Atlas of Weak Signals.md
#      - Areas of Interventions: DS/02-Areas of Interventions.md
      - Bio & Agri 0: Term1/02-Bio Agri0.md
      - Roles of Prototyping: DS/03-Roles of Prototyping.md
      - Living with your own Ideas: Term1/03-Living with your own Ideas.md
      - Documentation Communication: DS/04-Documentation.md
      - Tech beyond the Myth: Term1/04-Tech beyond the Myth.md
      - Community Engagement: Term1/05-Community Engagement.md
      - Extended Intelligences: Term1/06-Extended Intelligences.md
    - Term 2:
      - Reframing by reflecting: DS-T2/01-Reframing by Reflecting.md
      - Designing Next Billion Sec: Term2/02-Designing Next Billion Seconds.md

  - Interventions:
    - Term 1:
      - Daily Clay Interaction: INT/01-Daily Clay Interaction.md
      - To Pottery with Love: INT/02-Pottery with Love.md
      - Where Clay comes From?: INT/03-Where Clay comes From.md
#    - Term 2:

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
#    - icon: fontawesome/brands/medium
#      link: https://medium.com/
    - icon: fontawesome/solid/link
      link: "https://www.paresmarc.com/"
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/mrcprs/"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/mrcprs"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/paresmarc"
#    - icon: fontawesome/brands/github
#      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
#    primary: black
  font:
    # See available fonts at https://fonts.google.com/
#    text: Be Vietnam
    text: Montserrat
    code: Cutive Mono

  logo: images/tetra_logo.png
  favicon: images/mrcprs.jpg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true
  - toc:
      permalink: false
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
