# Replace the text below to customize your site
site_name: Marc Parés - Iaac
site_description: Master in Design for Emergent Futures
site_author: Marc Parés
copyright: Marc Parés  ©  2022
repo_name: 'Marc Parés'
site_url: 'https://paresmarc.github.io/MDEF/'
repo_url: 'https://paresmarc.github.io/MDEF/'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Design Studio:
      - Bootcamp: DS/01-Bootcamp.md
      - Areas of Interventions: DS/02-Areas of Interventions.md
      - Roles of Prototyping: DS/03-Roles of Prototyping.md
      - Documentation and Communication: DS/04-Documentation and Communication.md
  - Reflections :
      - Term 1:
          - AoWS: Term1/01-Atlas of Weak Signals.md
          - Bio & Agri 0: Term1/02-Design Studio.md
          - Living with your own Ideas: Term1/03-Living with your own Ideas.md

#      - Term 2:
#          - digi: term1/01-Bootcamp.md
#          - studio: term1/01-Bootcamp.md


extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
#    - icon: fontawesome/brands/medium
#      link: https://medium.com/
    - icon: fontawesome/solid/link
      link: "https://www.paresmarc.com/"
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/mrcprs/"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/mrcprs"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/paresmarc"
#    - icon: fontawesome/brands/github
#      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black
    accent: teal
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono

  logo: images/tetra_logo.png
  favicon: images/mrcprs.jpg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true
  - toc:
      permalink: false
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
